# -*- mode: ruby -*-
# vi: set ft=ruby :
# vi: set nu :

PROJECT_NAME = "mongo"

Vagrant.configure(2) do |config|

  config.vm.define 'mongo' do |mongo|
    mongo.vm.provider 'docker' do |docker|
      docker.image = "mongo"
      docker.name = PROJECT_NAME
      docker.ports = ["27017:27017"]
      docker.create_args = [
        '--volume=/etc/localtime:/etc/localtime:ro'
      ]
    end
  end

end
