# -*- mode: ruby -*-
# vi: set ft=ruby :
# vi: set nu :

Vagrant.configure(2) do |config|

  auth = {
      USER: "postgres",
      PASS: "postgres",
  }

  # Postgres 9.5
  config.vm.define 'postgres95' do |postgres|
    postgres.vm.provider 'docker' do |docker|
      docker.image = "postgres:9.5"
      docker.name = 'postgres95'
      docker.ports = ["5432:5432"]
      docker.build_args = [
          "postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
      ]
      docker.create_args = [
          '--volume=/etc/localtime:/etc/localtime:ro'
      ]
      docker.env = auth
    end
  end

  # Postgres 9.6
  config.vm.define 'postgres96' do |postgres|
    postgres.vm.provider 'docker' do |docker|
      docker.image = "postgres:9.6"
      docker.name = 'postgres96'
      docker.ports = ["5432:5432"]
      docker.build_args = [
          "postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
      ]
      docker.create_args = [
          '--volume=/etc/localtime:/etc/localtime:ro'
      ]
      docker.env = auth
    end
  end

end
