#
# Makefile
# uralbash, 2017-03-20 13:43
#

all: build

build:
	docker build \
		-t uralbash/centos6-x86_64-qt5-static:latest \
		.

push:
	docker push uralbash/centos6-x86_64-qt5-static


# vim:ft=make
#
