#
# Makefile
# uralbash, 2017-03-20 13:43
#

build:
	docker build \
		-t uralbash/centos6-x86_i386-gcc-cpp11:latest \
		.

push:
	docker push uralbash/centos6-x86_i386-gcc-cpp11

run-bash:
	docker run -i -t uralbash/centos6-x86_i386-gcc-cpp11 /bin/bash


# vim:ft=make
#
