#
# Makefile
# uralbash, 2017-03-20 13:43
#

all: build

build:
	docker build \
		-t uralbash/centos6-x86_64-qt5-dynamic:latest \
		.

push:
	docker push docker pull uralbash/centos6-x86_64-qt5-dynamic


# vim:ft=make
#
