# -*- mode: ruby -*-
# vi: set ft=ruby :
# vi: set nu :

PROJECT_NAME = "firebird25sc"

Vagrant.configure(2) do |config|
  config.vm.synced_folder "/opt/firebird", "/opt/firebird",
    owner: "firebird",
    group: "firebird",
    mount_options: ["dmode=775,fmode=664"]

  fileConfig = File.join(Dir.pwd, "firebird.conf")

  # firebird
  config.vm.define 'firebird' do |firebird|
    firebird.vm.provider 'docker' do |docker|
      docker.image = "jacobalberty/firebird"
      docker.name = PROJECT_NAME
      docker.ports = ["3050:3050", "3060:3060"]
      docker.create_args = [
        '--volume=%s:/var/firebird/etc/firebird.conf' % fileConfig
      ]
      # docker.env = {
      #   ISC_USER: "sysdba",
      #   ISC_PASSWD: "123",
      # }
    end
  end
end
